# Generated by Django 2.1.10 on 2020-04-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredinents',
            new_name='ingredients',
        ),
    ]
